packages:
  - "packages/*"
  - "packages/studio/renderer"
  - "vendor/*"

onlyBuiltDependencies:
  - electron

catalog:
  react: "19.1.0"
  react-dom: "19.1.0"
  vite: "6.3.2"
  vitest: "3.1.1"
  typescript: "5.8.3"
  "@tanstack/react-router": "1.116.0"
