packages:
  - 'packages/*'
  - 'packages/studio/renderer'

onlyBuiltDependencies:
  - electron

catalog:
  react: '19.1.0'
  react-dom: '19.1.0'
  vite: '6.3.2'
  typescript: '5.8.3'
  '@tanstack/react-router': '1.116.0'
